### ISSUE TITLE
go build main.go

### ISSUE THREAD

**Issue by remotejob** [owulveryck/charRNN#1]
`./main.go:77:26: model.Train undefined (type *lstm.Model has no field or method Train)`

???

**Comment by owulveryck** [comment]
Hello,
This repo is a work in progress,
Sadly I had no time recently to work on it recently.
As I was stuck with the LSTM implementation, I wrote a helper tool transcode the mathematical equation directly into code. This has been blogged [here](https://blog.owulveryck.info/2017/12/18/parsing-mathematical-equation-to-generate-computation-graphs---first-step-from-software-1.0-to-2.0-in-go.html).
I will try to work on the example within this month.
